### ISSUE TITLE
"PlotSquaredHandler.canUseAoe" should be improved!

### ISSUE THREAD

**Issue by ailanlana** [EverNife/FinalForgeRestrictor#1]
It's true that the area around a plot can't be destroyed by other players.However, the owner of the plot itself can use the aoe to destroy the plot road

**Comment by ailanlana** [comment]
Detection of aoe item should also require BlockBreakEvent, as currently there is only PlayerInteractEvent where the player can stand outside of the detection range and destroy squares within the detection range in order to destroy the territory.

**Comment by EverNife** [comment]
I think the best approach to fix AOE is to check if the player is fully inside his claim, so, if any of the corners is not inside HIS plot cancel the event.

**Comment by ailanlana** [comment]
I think you've made a good suggestion.The second one I forgot to mention is in the context of GriefPreventionPlus, my server has PlotSquared on one zone and GriefPreventionPlus on the other, and I've solved the problem perfectly by judging the block destroying events!

**Comment by EverNife** [comment]
not all AOE blocks fire block breat events.

Have you forked the project? maybe you can show me what you did for me to take a look

**Comment by EverNife** [comment]
Tried to implement the idea at https://github.com/EverNife/FinalForgeRestrictor/releases/tag/2.0.3

**Comment by ailanlana** [comment]
It's running well now, thank you! I'll keep you posted if I have any questions.
